apiVersion: 1
datasources:
  - name: Neo4j
    type: grafana-neo4j-datasource
    access: proxy
    url: bolt://neo4j:7687
    jsonData:
      database: neo4j
    secureJsonData:
      password: skandashield-change-me
    editable: true
